import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

part 'database.g.dart';

class TestResults extends Table {
  // Session id generated by the engine; also links the raw samples.
  TextColumn get id => text()();

  DateTimeColumn get startedAt => dateTime()();
  IntColumn get durationSeconds => integer()();
  RealColumn get distanceMeters => real()();

  // False when the test was aborted before the six minutes were over.
  BoolColumn get completed => boolean()();

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('SensorSampleRow')
class SensorSamples extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get sessionId => text()();
  DateTimeColumn get timestamp => dateTime()();
  TextColumn get sensorId => text()();
  TextColumn get sampleType => text()();

  // Measurement values as JSON map, so every sample type fits one table.
  TextColumn get valuesJson => text()();
}

class Profiles extends Table {
  // Single-row table: the one local user profile always has id 1.
  IntColumn get id => integer()();

  RealColumn get weightKg => real().nullable()();
  RealColumn get heightCm => real().nullable()();
  IntColumn get birthYear => integer().nullable()();
  TextColumn get sex => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

@DriftDatabase(tables: [TestResults, SensorSamples, Profiles])
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.e);

  AppDatabase.open() : super(driftDatabase(name: 'six_minute_walk_test'));

  @override
  int get schemaVersion => 1;
}
